base_url = "https://about.bofe.app"

build_search_index = false
compile_sass = false
default_language = "en"
minify_html = true

[markdown.highlighting]
theme = "catppuccin-mocha"

[translations]
lang-name = "English"

description = "With Bofe you can easily build kanban style boards for your projects, personal workflows, or just for fun."
get-it-on-google-play = "Get it on Google Play"
go-to-web-app = "Go to web app"
home = "Home"
or = "or"
privacy-policy = "Privacy Policy"
roadmap = "Roadmap"
tagline = "Kanban style boards"
terms-of-service = "Terms of Service"
version = "Version"

[languages.es.translations]
lang-name = "Español"

description = "Con Bofe puedes crear facilmente tableros al estilo kanban para tus proyectos, flujos personales, o simplemente por diversión."
get-it-on-google-play = "Obtenla en Google Play"
go-to-web-app = "Ir a la web app"
home = "Inicio"
or = "o"
privacy-policy = "Política de Privacidad"
roadmap = "Roadmap"
tagline = "Tableros al estilo kanban"
terms-of-service = "Términos de Servicio"
version = "Versión"

[extra]
version = "0.0.0-alpha.1"
